server: 
  port: 9004
spring: 
  application:  
    name: social-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.223.91:3306/social_article?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: Iloveyou0.
  jpa: 
    database: MySQL
    show-sql: true

  data:
    mongodb:
      host: 47.102.223.91
      port: 27017
      database: social-dev
      username: guest
      password: guest

redis:
  host: 47.102.223.91 # Redis服务器地址
  database: 0 # Redis数据库索引（默认为0）
  port: 6300 # Redis服务器连接端口
  password: Iloveyou0. # Redis服务器连接密码（默认为空）
  jedis:
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
  timeout: 3000ms # 连接超时时间（毫秒）